version: 2.1
 
jobs:
  build:
    docker:
      - image: cimg/node:16.13.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: node --version
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{‌{ checksum "package.json" }}
            - app-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: app-{‌{ checksum "package.json" }}

  linting:
    docker:
      - image: cimg/node:16.13.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: node --version
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{‌{ checksum "package.json" }}
            - app-
      - run:
          name: JS Linting Check
          command: yarn run lint

  prettier:
    docker:
      - image: cimg/node:16.13.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: node --version
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{‌{ checksum "package.json" }}
            - app-
      - run:
          name: Run Prettier Check
          command: yarn run prettier:check

  deploy-to-heroku:
    docker:
      - image: cimg/node:16.13.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: node --version
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Deploy to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]
            then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/moviesfx.git ${CIRCLE_BRANCH}:master -f
            else
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/moviesfx-dev.git ${CIRCLE_BRANCH}:master -f
            fi
 
workflows:
  build_and_deploy:
    jobs:
      - build
      - linting:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - main
      - prettier:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - main
      - deploy-to-heroku:
          requires:
            - linting
            - prettier
          filters:
            branches:
              only:
                - develop
                - main